spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**,.h2.server.properties
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:my_admin}
    password: ${POSTGRES_PASSWORD:my_password}
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
flyway:
  url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
  schemas: public
  user: ${POSTGRES_USER:my_admin}
  password: ${POSTGRES_PASSWORD:my_password}
