version: '3.8'
services:
  postgres:
    container_name: postgresql-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: deutsche_bank_demo
      POSTGRES_USER: my_admin
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
        - postgresql-db:/var/lib/postgresql/data
    networks:
        - postgresql-network
volumes:
    postgresql-db:
networks:
    postgresql-network:
        driver: bridge
